version: '3'
services:
  oidoypaz:
    image: mantis/oidoypaz
    volumes:
      - ../../:/app/
    ports:
      - "8002:8000"
    container_name: oidoypaz
    restart: on-failure
    environment:
      - TERM=xterm
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_OIDOYPAZ=${DB_OIDOYPAZ}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    depends_on:
      - oidoypaz-postgresql
    networks:
      - oidoypaznet
  oidoypaz-postgresql:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_OIDOYPAZ}
    container_name: oidoypaz-postgresql
    networks:
      oidoypaznet:
        aliases:
          - oidoypaz-postgresql
    volumes:
      - ../../.data/oidoypaz-postgres:/var/lib/postgresql/data
networks:
   oidoypaznet:
     external: true
